### ISSUE TITLE
CameraSLM simulation

### ISSUE THREAD

**Issue by cpanuski** [QPG-MIT/slmsuite#15]
Add ability to implement all CameraSLM functionality (e.g. wavefront correction) on a simulated camera and SLM. Useful for testing and implementing new wavefront correction algorithms. 

TODO:

- [x] Simulated camera base implementation
- [x] Simulated SLM base implementation
- [x] Change magnification parameter to focal length in simulated camera
- [x] Check automatic padding computations
- [x] Clean up sim tutorial

**Comment by LiuTongZan** [comment]
Dear @cpanuski ：
  I want to see the simulation effect, but two files **from slmsuite.hardware.slms.simulated import SimulatedSLM** and **from slmsuite.hardware.cameras.simulated import SimulatedCam** do not exist, can you help me solve it.
  Appreciate your help.
  Thanks and regards.

**Comment by ichristen** [comment]
Hi @LiuTongZan ,

Are you using the `sim` branch? These changes on this branch have not yet been merged into `main`. You will need to pull directly from `git` (`git clone`) to be able to checkout (`git checkout sim`) these features. The `pip` version will use the as-released `main` branch. Keep in mind that this is a development branch and features might be changed and/or renamed as they are polished.

Let us know if you have any ideas or suggestions regarding the `sim` branch. Just to list a few things that we've discussed adding:

- [ ] Simulation of camera noise (readout, dark current, etc).
- [ ] Simulation of SLM pixel crosstalk (due to the fringing field of the liquid crystal).
- [ ] Simulation of SLM phase nonlinearity, potentially per-pixel.

Hope this helps!

Best,
Ian

**Comment by cpanuski** [comment]
Basic functionality added in #52. Camera/SLM non-idealities discussed above will be added on an "as-needed" basis.
