### ISSUE TITLE
_phase2gray 

### ISSUE THREAD

**Issue by LeoKonzett** [QPG-MIT/slmsuite#19]
Hello,

I have a question for the `_phase2gray()` method in the `slm.py` file. There, we pass `self.display` as the `out` variable, and `self.display` has (depending on the SLM bit-resolution) a data-type `np.unint8` or `np.uint16`.

Later, the float -> int conversion gets enforced with `np.copyto(*args, casting="unsafe")`. 
Two questions: 

1. When `out` in `np.copyto` has 8-bit unsigned integer types, I think the subsequent call of `np.bitwise_and()` becomes irrelevant.
2. `np.copyto` casts e.g. `1.9` -> `1`. Shouldn't `2` be desired?
3. Also, casting negative integers to unsigned types can lead to unexpected behavior, e.g. `-162 -> 256 - 162 = 94`

I hope I got this right. Is the reason for using `np.copyto` speed because it's in-place? Otherwise, it seems a bit unsafe to do.

**Comment by ichristen** [comment]
Hi @LeoKonzett , thanks for this great question.

1. The `np.bitwise_and()` performs the action of `np.mod()` in the case when `self.phase_scaling == 1`. This is super fast compared with `np.mod()`. However, you're completely right that this call is unnecessary in the case where you have an 8-bit or 16-bit SLM, as the type casting already performs the `and`. I have added a check to not do this in those cases (6ece4bb297ea63ed0664cf1d2f03470002586bd8).
2. The intent was to avoid `np.around` overhead. We could accomplish the same thing by adding .5 before type-casting, but I'm uncertain whether it's worth the overhead for this fractional change. I have added documentation (6ece4bb297ea63ed0664cf1d2f03470002586bd8) specifying the `floor()`ed behavior.
3. In testing, I wasn't able to find a case where unsafe casting didn't behave like `floor()`, but if you can find one then I agree that a better solution is needed. I agree that the ironic `"unsafe"` flag correctly implies lack of safety, but I think it's deterministic in our case. Note that [this line](https://github.com/QPG-MIT/slmsuite/blob/main/slmsuite/hardware/slms/slm.py#L410) makes sure that all numbers are negative. The example that you gave is desired behavior, because this is the effect of `mod` by 256.

To answer your last question, yes the reasoning is speed. While something similar to this could be faster (like the ultimate solution for speed: going full-C and writing directly to some integer buffer and never touching floats), this solution was able to maintain both the 60 Hz operation in testing and the user-friendly 2pi float submission that we wanted to have. `np.mod()` was a main limitation for other implementations. Of course, we welcome any contributions to make the package better. If you have any ideas for how to improve this while still maintaining speed, feel free to discuss or add something! Let me know if you have any comments on the mentioned changes (6ece4bb297ea63ed0664cf1d2f03470002586bd8), we'll probably pull request this within a week.

**Comment by ichristen** [comment]
I'm closing this issue as these changes were pulled under request #24.

Please feel free, @LeoKonzett, to reopen it or to contact us about anything else! Looking forward to see what you do with the package.
