### ISSUE TITLE
wavefront_calibrate()

### ISSUE THREAD

**Issue by KaizhaoWang** [QPG-MIT/slmsuite#40]
1. Wondering whether it is typo in cameraslms.py file line 718

phase_correction = self.slm.measured_amplitude

maybe should be the following?

phase_correction = self.slm.phase_correction

2. If I only want to get the amplitude measurement from the wavefront_calibrate(), why the returned value is from Step 1.25 in the measure() function, so before the correction of the blazing angle, rather than after step 1.5?

**Comment by ichristen** [comment]
Hi Kaizhao,

Sorry for my late reply. Thanks for reaching out and taking a look at our package!

1. You are absolutely correct. This is a typo. Fixed in 4815ce8.

2. The k-vector blaze correction applied in step 1.5 is minor, usually corresponding to a shift across a small fraction (<<10%) of the span of the square window which captures the target diffraction pattern. Thus, to save time we determined that it was better to avoid taking another image as we have already captured basically the same data. Let us know if you observe something different, and we can move things around.

We're excited to see your active fork and look forward to seeing what you do with the package!
