### ISSUE TITLE
Issues for adding header and dll files in python 3.7 or earlier

### ISSUE THREAD

**Issue by tpr0p** [QPG-MIT/slmsuite#6]
### Discussed in https://github.com/QPG-MIT/slmsuite/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **YuanLi-sz** October 26, 2022</sup>
Hi,

The current error i am getting when I try to initialize slm is "'slm_funcs' is not defined".
I am using python3.7 and I found in both santec.py and _slm_win.py they are using 'add_dll_directory' and i think python3.7 doesn't support this, so this should be the reason for the error. Does this conclusion seems reasonable to you? And besides switching to python3.8 or newer do you have other suggestions for fixing this issue?

Thank you very much!</div>

**Comment by ichristen** [comment]
Hi @YuanLi-sz, I added a patch for python versions < 3.8 on a separate branch `add_dll` (commit 64038e7297afa6d35c4be686a6c36ecc1a6018ab). If you could test this to make sure that it works on your system (`git checkout add_dll`), then we will pull this change into main. Hope this helps, and let us know if you run into any further issues! We're still in the pre-release stage, but will do a PiPy release once we've finished polishing, documentation, examples, etc.

**Comment by YuanLi-sz** [comment]
> 

Hi @ichristen, thank you for the patch! 
I am using an Applied Vision camera and Vimbapython so I didn't test the thorlabs.py, but the _slm_win.py patch is not working. The _slm_win.py is still reporting an error as following:

PS C:\Users\SLM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages> & C:/Users/SLM/AppData/Local/Microsoft/WindowsApps/python3.7.exe c:/Users/SLM/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0/LocalCache/local-packages/Python37/site-packages/slmsuite/hardware/slms/_slm_win.py
Traceback (most recent call last):
  File "c:/Users/SLM/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0/LocalCache/local-packages/Python37/site-packages/slmsuite/hardware/slms/_slm_win.py", line 38, in <module>
    _libraries[_libname] = windll.LoadLibrary(_libname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__  
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found


I am very certain that both the dll files are in the same directory:

PS C:\Users\SLM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\slmsuite\hardware\slms> ls

    Directory: C:\Users\SLM\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\ 
    slmsuite\hardware\slms

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/26/2022   6:42 PM                __pycache__
-a----         3/16/2018   9:18 AM         207360 FTD3XX.dll
-a----        10/28/2022   2:31 PM            101 PyCheck.py
-a----         11/3/2022   5:55 PM           9680 santec.py
-a----        10/14/2022   1:57 PM          15250 screenmirrored.py
-a----        10/14/2022   1:57 PM          15518 slm.py
-a----         7/13/2021  11:12 AM         375808 SLMFunc.dll
-a----         11/3/2022   5:49 PM          14095 _slm_win.py
-a----        10/25/2022   6:43 PM             89 __init__.py

I also tried directly adding the file to the library and doing a os.chdir() but both didn't work out.

**Comment by ichristen** [comment]
Hi @YuanLi-sz ,

That error [suggests](https://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found) that there might be some issue with .dll dependencies. That is to say, Santec's .dll is linked to other .dlls, but it's having trouble finding these other .dlls. I would suggest two parallel approaches to resolve this:

- Did you install Santec's GUI? It comes on a USB disk with the SLM. I think the installer will cover all the dependencies. You should also use this vendor GUI to make sure the SLM is working.
- I have had luck with using [Dependency Walker](https://www.dependencywalker.com/) to trace .dll linkages and find what's causing such opaque errors. Dependency Walker will show you what dependencies are successfully found, and what dependencies are not found.

Hope this helps!

Also, @tpr0p , I didn't internalize how awkward putting the .dlls into pip install directories would be (we generally work off of the repo directly). Maybe we should revisit where .dlls should go (maybe in the same directory as the root script?).

**Comment by ichristen** [comment]
Hi @YuanLi-sz , sorry for my late reply. Were you able to get Santec's GUI to work? I would suggest this as a first step.

**Comment by YuanLi-sz** [comment]
@ichristen Sorry i for got to mention that. Yes the GUI is working good, and I have another program program based on wxpython also works.

**Comment by ichristen** [comment]
@YuanLi-sz 
This is an interesting problem. You might consider the following course of action:

- I wouldn't erase the computer just yet. Consider instead installing a new python environment via [anaconda](https://www.anaconda.com/products/distribution). Then use `pip` to install `slmsuite` on the environment. I'm not precisely sure how .dll dependencies are looked up, but this might help with that.
- Consider trying a different computer. This will help to isolate the problem. We have not encountered this issue after testing on order ten different computers (running Windows 7, 10, 11). It will be interesting if the problem occurs again. Maybe a faulty .dll?
- If the above doesn't work, I would E-mail Santec to see if they have any ideas. At this point, it seems like the .dll is failing, so I don't know what else to do python-side.
- If you're interested in using features inside `slmsuite`, you can use the `ScreenMirrored` interface instead of `Santec`. `ScreenMirrored` does not currently support >8bit operation or allow the user to set the Santec wavelength lookup table, however.

**Comment by YuanLi-sz** [comment]
HI @ichristen,
Thank you so much for all these suggestion!
Actually i have already started the the resetting in 30 minutes ago. I have considered about using the anaconda earlier but there're five versions of Pythons in this laptop and this is the only available computer for SLM control so I would rather just reset everything since I would need to do this sooner or laster. 
Thanks again for all the help!

**Comment by ichristen** [comment]
Closing this issue due to #13, which should eliminate the original python<3.7 issue. @YuanLi-sz , let us know if you got things working, or if you'd like to discuss more!
