### ISSUE TITLE
Wavefront calibration over a field of view

### ISSUE THREAD

**Issue by tpr0p** [QPG-MIT/slmsuite#60]
Measure/estimate the optical transfer function between the SLM and the camera. Has been explored by [Kavakli et al.](https://github.com/complight/realistic_holography).

**Comment by ichristen** [comment]
There’s a bit to talk about here.

- First, `odak` operates in a different regime than we do. Look at Fig. 1 in the linked paper. Their hologram is actually a nearfield hologram filtered by a pinhole. This problem is a much easier problem than the farfield holography that slmsuite focuses on (though it would be cool to add nearfield stuff too). The transfer function is much simpler because it is nearfield.
- The current wavefront calibration routines in slmsuite calculate the farfield kernel (corresponding to the phase correction / measured amplitude plus a FFT) at a single k-vector. This is valid at this single k-vector, but the full complex kernel requires the phase corrections for every k-vector.
- We discussed, in a separate channel, the `slmsuite` roadmap to resolve this. Maybe coming next release!
- At one point, I thought that taking `odak`'s approach was the way to go (#32), but since changed my mind to take the more numerical direction based on measured results rather than physics-based approximations because I think this approach is more tractable and easier to compute.

**Comment by tpr0p** [comment]
@ichristen why was this closed?
