### ISSUE TITLE
Numpy 2.0.0 support

### ISSUE THREAD

**Issue by JMHeidweiler** [QPG-MIT/slmsuite#73]
Are there any plans to support numpy 2.0.0?

Numpy 2.0.0 introduced a lot of new features, but also breaking changes.

E.g., running the second cell in the `slmsuite-examples/computational_holography.ipynb` notebook results in the following error, when cupy is not installed:

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword."

![grafik](https://github.com/user-attachments/assets/28fe176f-cae4-403d-b2a2-c37d2bc1e7d2)

**Comment by ichristen** [comment]
Hi @JMHeidweiler ,

numpy 2.0.0+ is already fixed on `dev` 13035a04f81abc9d02939d01171c8274bf45e119 #69 !

I followed their [migration guide](https://numpy.org/devdocs/numpy_2_0_migration_guide.html) (although it seems that `complex.real` and `complex.imag` still work, so I'm keeping that in because it's more efficient).

We're doing a #69 release review this weekend or Monday, so it should be out soon. In the meantime, please either downgrade numpy or switch your branch to `dev`. There might be a few remaining bugs on `dev` (including a few breaking changes that will make the old examples not work).

Thanks for your interest in `slmsuite`!

Best,
Ian

**Comment by ichristen** [comment]
I'm leaving this issue open until #69 is out.

**Comment by ichristen** [comment]
n.b. moving to `copy=None` is not backwards-compatible with numpy 1.x.x, as I learned, so I modified the fix to be backwards compatible with the numpy version 6a890a016e5c7b4657b5aae848eab5f36b95cf56.

Though in retrospect, this will break if numpy ever gets above version 9, so maybe I should add a check for `version[:2] == "1."` instead of `version[0] == "1"`.
