### ISSUE TITLE
spot array generates non-uniform pitch spot arrays

### ISSUE THREAD

**Issue by tpr0p** [QPG-MIT/slmsuite#8]
As of
a3750006b10d301ed08a0a5c3c2dfe88c5230fab

See
https://drive.google.com/file/d/1ETdWihIc-QpywtLbokbTRt6uHXcsMk25/view?usp=share_link

**Comment by ichristen** [comment]
Hmm. I think this is actually intended behavior. Looks like integer rounding to me, where the upper spots happened to be rounded up one in the (integer) computational k-space `knm`.

Internally, a grid is created in `.make_rectangular_array()` from x and y lists on each edge:
```
x_edge = (np.arange(array_shape[0]) - (array_shape[0] - 1) / 2)
x_edge = x_edge * array_pitch[0] + array_center[0]
y_edge = (np.arange(array_shape[1]) - (array_shape[1] - 1) / 2)
y_edge = y_edge * array_pitch[1] + array_center[1]
```
But then, the points generated from these edges are `ceil`ed up.
```
self.spot_knm_rounded = np.ceil(shape / 2 + self.spot_knm.astype(np.float))
self.spot_knm_rounded = self.spot_knm_rounded.astype(np.int)
```
The fix is either to increase the resolution of k-space to be finer (and the off-by-one less noticeable, or choose `array_shape` and `array_center` more carefully to avoid undesirable rounding.

Rounding is going to happen no matter what, which is why this is intended behavior. I added a user info note in 7a84c9c732d894049dc97991aec75bc8d9d432a3.

**Comment by tpr0p** [comment]
I realized this would affect results of fourier calibration so I spent some more time thinking about it. I am proposing that we adopt the convention I declared here:
https://github.com/QPG-MIT/slmsuite/blob/eb0316cd2612c2dfbce9129a2145a1ce8dd9c108/slmsuite/holography/toolbox.py#L4

The x_edge and y_edge computation is fine because the results are floats with uniform pitch. I think `spot_knm_rounded` is funky due to the `ceil`. For example,  say `shape / 2 + self.spot_knm.astype(np.float))` has x coords 58.6, 64, 69.4: 58.6 is rounded up to 57, 64 stays, 69.4 is rounded up to 70, so the array isn't uniform anymore. You can prove by considering a few simple cases that under this convention two points equally spaced about zero (58.6 ~ -5.4) and (69.4 ~ 5.4) always end up an equal number of indices away from zero. The thing that gets rounded in a non-deterministic way is the offset index where zero is. I'll keep the note you wrote and add a link to the toolbox note in docs.

**Comment by ichristen** [comment]
The `ceil` was intended to make the rounding explicit. The rounding has to occur no matter what to generate an image in computational k-space. I'm not sure if the proposed convention resolves the problem, as you're back to non-uniform pitch once you do more than three points in the example (e.g. five points). The heart of the issue was passing a non-integer `knm` pitch in the first place, I would argue, which is a user issue that we can (at best) warn about.

**Comment by ichristen** [comment]
But in retrospect, `round` probably produces better results in the case of `spot_knm_rounded`. See https://github.com/QPG-MIT/slmsuite/commit/2a958cc8b28c360091f9d6788ed9da1d20cd7ff1.
